### ISSUE TITLE
deskreen crashes.

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1164]
Deskreen crashes on the new Version of Raspberry Pi OS with Bullseye. Here is the log:

```
pi@raspberrypi:~ $ deskreen
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE: address already in use :::3131
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at e.value (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:61573)
    at e.<anonymous> (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:61347)
    at c (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:1775317)
    at Generator._invoke (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:1775070)
    at Generator.next (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:1775676)
    at rt (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:58468)
    at i (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:58672)
19:14:24.708 › Checking for update

(deskreen:8350): libnotify-WARNING **: 19:14:25.338: Failed to connect to proxy

(deskreen:8350): libnotify-WARNING **: 19:14:25.347: Failed to connect to proxy

(deskreen:8350): libnotify-WARNING **: 19:14:25.352: Failed to connect to proxy
19:14:25.733 › Error: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml): HttpError: 404 
"method: GET url: https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Sun, 14 Nov 2021 18:14:07 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "CE64:B82B:523FFF1:57E56E0:61915201"
}
    at f (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:144671)
    at i.handleResponse (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:146294)
    at ClientRequest.<anonymous> (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:145763)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at t.newError (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:152011)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:566939)
    at p.getUpdateInfoAndProvider (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:519151)
    at p.doCheckForUpdates (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:519437)
(node:8350) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml): HttpError: 404 
"method: GET url: https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Sun, 14 Nov 2021 18:14:07 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "CE64:B82B:523FFF1:57E56E0:61915201"
}
    at f (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:144671)
    at i.handleResponse (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:146294)
    at ClientRequest.<anonymous> (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:145763)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at t.newError (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:152011)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:566939)
    at p.getUpdateInfoAndProvider (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:519151)
    at p.doCheckForUpdates (/tmp/.mount_DeskregEq34A/resources/app.asar/main.prod.js:2:519437)
(node:8350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
c^Cpi@raspberrypi:~ $ 

```

**Comment by cycool29** [comment]
I can reproduce this on my RPi OS armv7l bullseye. That seems to be problem of electron sandbox. Using `--no-sandbox` flag worked for me. 

Opened a PR [here](https://github.com/Botspot/pi-apps/pull/1166).

**Comment by KolpixTV** [comment]
```
pi@raspberrypi:~ $ deskreen --no-sandbox
16:13:13.119 › /tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js : Deskreen signaling server is online at port 3131
16:13:14.191 › Checking for update

(deskreen:3329): libnotify-WARNING **: 16:13:14.547: Failed to connect to proxy

(deskreen:3329): libnotify-WARNING **: 16:13:14.552: Failed to connect to proxy

(deskreen:3329): libnotify-WARNING **: 16:13:14.560: Failed to connect to proxy
16:13:14.848 › Error: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml): HttpError: 404 
"method: GET url: https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Mon, 15 Nov 2021 15:13:03 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ADD0:B236:5676A2:5D6528:6192790A"
}
    at f (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:144671)
    at i.handleResponse (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:146294)
    at ClientRequest.<anonymous> (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:145763)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at t.newError (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:152011)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:566939)
    at p.getUpdateInfoAndProvider (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:519151)
    at p.doCheckForUpdates (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:519437)
(node:3329) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml): HttpError: 404 
"method: GET url: https://github.com/pavlobu/deskreen/releases/download/v1.0.11/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Mon, 15 Nov 2021 15:13:03 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ADD0:B236:5676A2:5D6528:6192790A"
}
    at f (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:144671)
    at i.handleResponse (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:146294)
    at ClientRequest.<anonymous> (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:145763)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at t.newError (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:152011)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:566939)
    at p.getUpdateInfoAndProvider (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:519151)
    at p.doCheckForUpdates (/tmp/.mount_Deskre55JS7S/resources/app.asar/main.prod.js:2:519437)
(node:3329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[3329:1115/161317.138874:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
/usr/local/bin/deskreen: Zeile 2:  3329 Trace/Breakpoint ausgelöst   /home/pi/.Deskreen/Deskreen-1.0.1-armv7l.AppImage

```

it still does not work for me even with the --no-sandbox flag and also without it

**Comment by Crilum** [comment]
@KolpixTV Try `$HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage --no-sandbox`. It works for me. The `deskreen` command is created by the install script, and it just executes deskreen without `--no-sandbox`, so even it you run `deskreen --no-sandbox`, it still just runs `$HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage`, no matter what you do.

**Comment by KolpixTV** [comment]
thank you this works fine :D
