### ISSUE TITLE
Adding Mindustry 

### ISSUE THREAD

**Issue by Fuckashi** [Botspot/pi-apps#1183]
Hy
I saw someone who compiled mindustry (that works) but it's an old version.
Will it be possible to look at its shell code to create an updated version and publish it on pi-apps ? 

Link: 
[https://github.com/azureblue/MindustryPi](url)
[https://github.com/Anuken/Mindustry](url)

**Comment by ryanfortner** [comment]
Duplicate of https://github.com/Botspot/pi-apps/issues/1186

**Comment by Fuckashi** [comment]
no i'm first

**Comment by cycool29** [comment]
The script of https://github.com/azureblue/MindustryPi is outdated. The links in the script are not usable. So I tried to compile Mindustry from upstream repo, but ends up with this:
```
> Task :tools:pack FAILED
Exception in thread "main" arc.util.ArcRuntimeException: Couldn't load shared library 'libarcarm.so' for target: Linux, 32-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:84)
	at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:14)
	at mindustry.tools.ImagePacker.main(ImagePacker.java:28)
Caused by: arc.util.ArcRuntimeException: Unable to read file for extraction: libarcarm.so
	at arc.util.SharedLibraryLoader.readFile(SharedLibraryLoader.java:93)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:253)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 2 more

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/testdir/Mindustry/tools/build.gradle' line: 199

* What went wrong:
Execution failed for task ':tools:pack'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-armhf/bin/java'' finished with non-zero exit value 1

```

I can't find `libarcarm.so` in https://github.com/azureblue/Arc.

**Comment by smithmule** [comment]
does the bottom half of [build script](https://github.com/azureblue/MindustryPi/blob/main/build-for-pi.sh) have something to do with `libarcarm.so`
it looks like its renaming parts of a file? 
i wish i could help but this is all way beyond me :smile:

**Comment by theofficialgman** [comment]
This is a simple java application. Please open a PR or add a zip following other pi-apps jar based applications as example for installing java and this jar file.
