### ISSUE TITLE
mc server broken

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1411]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

forge crashes it

### Description

it will just crash

### What is your operating system?

raspberry pi os 32bit

### (Optional) Error log? Terminal output? Debug messages?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Pi-Apps local commit ID: 1530dc97cadc543a1535d0f4023a2905cbe07b62
Github latest commit ID: 1530dc97cadc543a1535d0f4023a2905cbe07b62	
Kernel: armv7l 5.10.63-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2
Ram size: 3.78 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

This script helps you setup a Minecraft-Java-Server (for any version).
Will install these packages: lsb-release wget gpg screen 
Running sudo apt update...
Hit:1 https://adoptium.jfrog.io/artifactory/deb buster InRelease
Hit:2 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:3 https://mcpi-revival.github.io/mcpi-packages buster InRelease
Hit:4 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Hit:6 http://raspbian.raspberrypi.org/raspbian buster InRelease
All packages are up to date.
apt update complete.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c25e8dc5
Depends: gpg, lsb-release, screen, wget
Installing the pi-apps-c25e8dc5 package...
The following additional packages will be installed:
  libutempter0 screen
Suggested packages:
  byobu | screenie | iselect
The following NEW packages will be installed:
  libutempter0 pi-apps-c25e8dc5 screen
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 199513 files and directories currently installed.)

Apt finished.
Package installation complete.
Adding Adoptium repository:
- public key -> keyring
Downloading public to /tmp/adoptium-public-key... 
?25h
Done
gpg: keybox '/tmp/adoptium-keyring.gpg' created
gpg: key 843C48A565F8F04B: public key "Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
 - keyring -> GPG key
 - Moving GPG key to /usr/share/keyrings
 - Creating /etc/apt/sources.list.d/adoptium.list
Will install these packages: temurin-8-jdk 
Running sudo apt update...
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 https://adoptium.jfrog.io/artifactory/deb buster InRelease
Hit:4 https://mcpi-revival.github.io/mcpi-packages buster InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
All packages are up to date.
apt update complete.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-c25e8dc5
The pi-apps-c25e8dc5 package is already installed. Inheriting its dependencies: gpg, lsb-release, screen, wget
Depends: gpg, lsb-release, screen, temurin-8-jdk, wget
Installing the pi-apps-c25e8dc5 package...
The following packages will be upgraded:
  pi-apps-c25e8dc5
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
apt-listchanges: Reading changelogs...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 199581 files and directories currently installed.)

Apt finished.
Package installation complete.
JVM info: Temurin - 1.8.0_312 - 25.312-b07
java.net.preferIPv4Stack=true
Exception in thread "main" 
joptsimple.UnrecognizedOptionException: install-server is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:89)
Failed to install forge server

Failed to install Minecraft Java Server!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by theofficialgman** [comment]
forge has a special case that runs its installer during the pi-apps script install
can you please respond which which forge server version you added?
it should have been named something like `forge-*-installer.jar`

**Comment by rbcoder117** [comment]
it is forge-1.12.2-14.23.5.2859-installer.jar

**Comment by theofficialgman** [comment]
oh, so apparently forge change the command from `--install-server` to --`installServer`. I don't know when that happened but it used to work. I'll update the script
