### ISSUE TITLE
How to run minecraft java versions 1.12.2 or older?

### ISSUE THREAD

**Issue by Strekano** [Botspot/pi-apps#161]
Hello i can't play minecraft java ,older minecraft versions, i have this error
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.lwjgl.DefaultSysImplementation.getPointerSize()I
	at org.lwjgl.DefaultSysImplementation.getPointerSize(Native Method)
	at org.lwjgl.Sys.<clinit>(Sys.java:118)
	at bib.I(SourceFile:2825)
	at net.minecraft.client.main.Main.main(SourceFile:38)
What muss i do to fix it? :/

**Comment by mobilegmYT** [comment]
Click edit profile in the launcher, go to JVM arguments, and change the "lwjgl3" to a "lwjgl2"

**Comment by Botspot** [comment]
Can @Strekano confirm the above suggestion is working?

**Comment by Strekano** [comment]
Yes its working  .Thanks
