### ISSUE TITLE
No working version of Tabby 64bit available

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1787]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Electron 18 can't be used on buster due to upstream bug

### Description

https://github.com/Jai-JAP/tabby-arm-builds

all the older releases here which were built before electron 18 produce errors for me:
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}

```
and we are unable to use the newer releases as they are built on electron 18

@Jai-JAP please implement the electron to 17 downgrade for arm64 and verify the newly produced debs work on buster 32/64bit

### What is your operating system?

buster/bionic/focal

**Comment by Jai-JAP** [comment]
@theofficialgman can you try again. I just uploaded the rebuilt versions

**Comment by theofficialgman** [comment]
@Jai-JAP you didn't actually upload rebuilt versions... you didn't trigger a build

**Comment by theofficialgman** [comment]
I also do not see any change to electron 17 for arm64, did you change anything?

**Comment by Jai-JAP** [comment]
Its already on electron 17.
See https://github.com/Jai-JAP/tabby/blob/780691413d6ec0fa82c591e51c2355d89d33e7dc/package.json#L37

**Comment by theofficialgman** [comment]
Have you forgotten how your own buildscript yml works? You clone from upstream `git clone https://github.com/Eugeny/Tabby.git`

**Comment by Jai-JAP** [comment]
What version of tabby r u using

**Comment by Jai-JAP** [comment]
v1.0.176 and v1.0.176 are being built with electron 17.x.y

Also the older tabby with electron 17 by default is rebuilt and pushed to the repo it should not cause any error. Can you try that again

**Comment by theofficialgman** [comment]
tested the new build of 1.0.176 arm64. its definitly build on electron 17 now since I don't get the linking error
but I'm still getting this
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```

**Comment by theofficialgman** [comment]
https://github.com/Eugeny/tabby/issues/6231

**Comment by Jai-JAP** [comment]
New builds are in progress

**Comment by theofficialgman** [comment]
🥳 works nowl, just tested the new 177 build. thanks @Jai-JAP 
I'll re-enable the updater in pi-apps
