### ISSUE TITLE
new update broke some pi apps apps

### ISSUE THREAD

**Issue by end3rchan** [Botspot/pi-apps#2023]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

some apps like armcord won't install and lunar client can't launch minecraft

### Description

my pi is a pi 4 with 4gb and recently there was a new rpi os update and now i can't launch minecraft with lunar client also armcord can't install anymore i tried updating apt updating the os updating pi apps and even getting a new rpi os on my pi and it still does the same thing does anyone know how to fix this?
![2022-07-04-103533_1680x1050_scrot](https://user-images.githubusercontent.com/99518396/177202865-f3a6a189-2511-47cd-a553-d6428369b59c.png)

### What is your operating system?

rpi os

### (Optional) Error log? Terminal output? Debug messages?

```bash
here is the latest logs for lunar client:
[2022-07-04 10:36:12.530] [info]  Starting IPC server.
[2022-07-04 10:36:12.546] [info]  Started IPC server.
[2022-07-04 10:36:13.990] [info]  (autoUpdater) Checking for update
[2022-07-04 10:36:15.353] [error] (autoUpdater) Error: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 04 Jul 2022 14:36:15 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=JyQkrruyq8XceHa7lsxt3Krj390hmT3RMSQD6D3dIUxdO75JuTPbTiAuopbjWvMbcRKjfP1H8NjgFQYjZYPptMXGaxTYDV7r%2BD4z6hfMJ7x9ZqkVKZ%2BkieK3QkxTG4DZoyf3LDQ8Z7oJSpQDv4c29JvTnp762PMKt3uSUFJ3p7%2FXl5oj3TtUuFI5ja2wow8Xut9yKr72VRswqtCeCCTWKzER0m3GdsC6GaKaHH5wD7PeXSP9EkNVhPozWZ81Ko6o2f1iVXvlAnROyXbOs6UQRA%3D%3D--fcLb6kBHiF5wDlQN--yh1RHuY%2BOmexLCGCXEq8aQ%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1853916091.1656945375; Path=/; Domain=github.com; Expires=Tue, 04 Jul 2023 14:36:15 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Tue, 04 Jul 2023 14:36:15 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "9088:3A5E:1122FC6:2520DD4:62C2FADE"
}
    at createHttpError (/tmp/.mount_lunarcP52Xti/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcP52Xti/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:158:9)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcP52Xti/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:113:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

**Comment by Botspot** [comment]
First of all, thank you for reaching out for help.

I will install Lunar Client on my machine and check if I can reproduce your error.

> also armcord can't install anymore

What was the error for installing ArmCord?

**Comment by end3rchan** [comment]
hum the armcord bug was actually a one time bug but it just seemed weird it happened at the same time so i taught it was link but i guess it wasn't

**Comment by end3rchan** [comment]
so yeah now armcord works

**Comment by Botspot** [comment]
> hum the armcord bug was actually a one time bug but it just seemed weird it happened at the same time so i taught it was link but i guess it wasn't

You can review past Pi-Apps logs by going into setting and clicking on the Log files button.

BTW, I was able to reproduce the Lunar Client error.

**Comment by end3rchan** [comment]
oh great! do you have a clue on why the bug is happening?

**Comment by gl91306** [comment]
the bug is fixed and the not connecting to github thing appears cause the wrong logs were pasted. this issue is resolved plz clsoe
