### ISSUE TITLE
Oomox Theme Designer: provide python 3.10+ for compatibility with future versions

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2297]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Error in terminal on startup

### Description

Does not work.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 04/06/2023
Latest Pi-Apps version: 04/06/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
oomox-gui
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/oomox/oomox_gui/__init__.py", line 11
    if (version := sys.version_info) < MIN_PYTHON_VERSION:
                ^
SyntaxError: invalid syntax
```

**Comment by theofficialgman** [comment]
please file this as a bug at the upstream project
https://github.com/themix-project/oomox

**Comment by theofficialgman** [comment]
if you check the code, that is supposed to be a python version checker script.
only python 3.10+ are supported by upstream it appears for a few months now https://github.com/themix-project/themix-gui/blob/master/oomox_gui/__init__.py#L10

**Comment by theofficialgman** [comment]
On ubuntu python3.10 can be obtained for bionic/focal from the deadsnakes ppa and it will not interfere with the default system python3 version (whatever version that may be)

will look into this for bionic/focal/buster/bullseye as none of them have python3.10+

**Comment by Rak1ta** [comment]
@theofficialgman Is it possible to temporarily make the repo download of [this version](https://github.com/themix-project/themix-gui/releases/tag/1.15.1)? It works. You updated the script to update the program, but the new version does not work. Just as a guess.

**Comment by theofficialgman** [comment]
> @theofficialgman Is it possible to temporarily make the repo download of [this version](https://github.com/themix-project/themix-gui/releases/tag/1.15.1)? It works. You updated the script to update the program, but the new version does not work. Just as a guess.

actually no the script just downloads the latest git repo version on installation. there is no updating or version downloading in it

we really need to go through all scripts and make sure this isn't the case

**Comment by theofficialgman** [comment]
now using 1.15.1 with this commit https://github.com/Botspot/pi-apps/commit/64bbda163cdd262476eeda81aa331af26b49be5d

leaving this issue open and changed to a suggestion so that we don't forget that eventually a new release of oomox theme designer will be released that requires 3.10+
