### ISSUE TITLE
M5Burner

### ISSUE THREAD

**Issue by matu6968** [Botspot/pi-apps#2695]
### What is the name of the app?

M5Burner

### Where is the app hosted?

decompiled version: https://github.com/matu6968/m5burner (this version will be used for the download process)
official version (available only for x64): https://docs.m5stack.com/en/download

### About the app

M5Burner is an app meant to flash M5Stack devices (like M5Stack StickC or M5Stack Core) that comes with a repository of firmware images meant for the M5Stack hardware. This includes M5Stack's own firmware (like UIFlow) and community made firmware (like [CatHack](https://github.com/Stachugit/CatHack) which mimics Flipper Zero's user interface or [Bruce](https://github.com/pr3y/bruce))

### Upload file or Add PR Link

[M5Burner.zip](https://github.com/user-attachments/files/18141843/M5Burner.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Thanks for working on the scripts. I have not tested them yet, but they appear high quality and assuming the app runs as it should, I have no issues adding it to Pi-Apps.
I have a few thoughts about the scripts though:
- `/home/${USER}/` can be replaced with `~/` when not within `"`.
- Towards the end you could replace that clunky `$?` if statement with:
```bash
if ! groups $USER | grep -q dialout ;then
```
- I am assuming this app will receive updates, right? Updates in Pi-Apps will trigger whenever the install script is updated. for an update, it runs the old `uninstall` script, and then runs the new `install-**` script. The way you currently have your uninstall script, it will ask permission to delete all cached data during an update. This user prompt will annoy and confuse users during updates. Consider doing what we do elsewhere for other apps:
  - Either leave cache/config data in place, and tell the user where to go to delete it (such as with the Tor Browser)
  - Or check if the `uninstall` and `install-**` script was given the `update` flag in `$1`, and if so, skip data removal lines with an `if` statement. (such as in with Better Chromium)

**Comment by matu6968** [comment]
> Thanks for working on the scripts. I have not tested them yet, but they appear high quality and assuming the app runs as it should, I have no issues adding it to Pi-Apps. I have a few thoughts about the scripts though:
> 
> * `/home/${USER}/` can be replaced with `~/` when not within `"`.
> * Towards the end you could replace that clunky `$?` if statement with:
> 
> ```shell
> if ! groups $USER | grep -q dialout ;then
> ```
> 
> * I am assuming this app will receive updates, right? Updates in Pi-Apps will trigger whenever the install script is updated. for an update, it runs the old `uninstall` script, and then runs the new `install-**` script. The way you currently have your uninstall script, it will ask permission to delete all cached data during an update. This user prompt will annoy and confuse users during updates. Consider doing what we do elsewhere for other apps:
>   
>   * Either leave cache/config data in place, and tell the user where to go to delete it (such as with the Tor Browser)
>   * Or check if the `uninstall` and `install-**` script was given the `update` flag in `$1`, and if so, skip data removal lines with an `if` statement. (such as in with Better Chromium)

Here is the fixed up version: 
[M5Burner.zip](https://github.com/user-attachments/files/18148483/M5Burner.zip)

**Comment by matu6968** [comment]
Sorry, i didn't properly check the updated script to see if it would error out. I deleted the broken version so here is the fixed up again version: 
[M5Burner.zip](https://github.com/user-attachments/files/18149037/M5Burner.zip)

**Comment by theofficialgman** [comment]
Any chance you can just build debs with https://classic.yarnpkg.com/en/package/electron-installer-debian ? You are doing a lot of things manually in these scripts that would just be automated by using that tool to build debs in the first place.

**Comment by matu6968** [comment]
> Any chance you can just build debs with https://classic.yarnpkg.com/en/package/electron-installer-debian ? You are doing a lot of things manually in these scripts that would just be automated by using that tool to build debs in the first place.

This does not work as electron-installer-debian assumes that everything is in the electron app which for M5Burner isn't as it needs esptool.py (+ nvs and the other python 3 dependencies it needs) and in that case trying to compile it will get you an error saying it can't find the resources folder: `Creating package (this may take a while)
Error: Could not determine resources directory in Electron app
    at /home/ximipi5/m5burner/node_modules/electron-installer-common/src/readmetadata.js:44:13
    at async /home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:135:21
    at async Promise.all (index 0)
    at async DebianInstaller.generateDefaults (/home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:134:42)
    at async module.exports (/home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:257:3) Error: Could not determine resources directory in Electron app
    at /home/ximipi5/m5burner/node_modules/electron-installer-common/src/readmetadata.js:44:13
    at async /home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:135:21
    at async Promise.all (index 0)
    at async DebianInstaller.generateDefaults (/home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:134:42)
    at async module.exports (/home/ximipi5/m5burner/node_modules/electron-installer-debian/src/installer.js:257:3)
`

**Comment by matu6968** [comment]
Updated 3.1.0 release for Pi-Apps: 

[M5Burner.zip](https://github.com/user-attachments/files/18895764/M5Burner.zip)

Also regarding this:

> Any chance you can just build debs with https://classic.yarnpkg.com/en/package/electron-installer-debian ? You are doing a lot of things manually in these scripts that would just be automated by using that tool to build debs in the first place.

1. This can be automated by specifying `deb` in the build linux package flags, but for a successful and functioning build this means everything (including flash tools and the UI) needs to be embedded in the .asar archive without having other folders but i need to solve 2. before going futher:
2. I would need to rewrite the code that handles the file paths and reading of the general UI elements, files and for caching i would instead have to utilize the native OS cache folders for every supported platform (in this case .cache folder in user root for Linux). 
For now since i don't want to deal with major breaking changes in the app, i will stick to what M5Stack did with folder placement and make the migration to the native cache folders in a later release (like 3.2.0)

**Comment by matu6968** [comment]
Closing issue for now as i currently don't focus on this fork anymore
