### ISSUE TITLE
OpenShot

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#301]
Can you add OpenShot to Pi-Apps, because the apt version is ancient, and I've tried (and failed) to get the newest version working on a Pi 4.

Thanks!

**Comment by fabianmendes** [comment]
did you check what does it need? Any dependences?? or what steps did you?
 ~V. Fabian T· Mendes C.

**Comment by Pythonic456** [comment]
Yes I did check what it needs, and even got to the point of trying to start it, when it falls over with this error:
```Loaded modules from: /usr/local/lib/python3.7/dist-packages/openshot_qt-2.5.1.dev2-py3.7.egg/openshot_qt
qt5ct: using qt5ct plugin
INFO app: ------------------------------------------------
INFO app:             Fri Jan 29 17:32:24 2021            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:          OpenShot (version 2.5.1-dev2)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.5.1-dev2
ERROR logger: Traceback (most recent call last):
ERROR logger:   File "/usr/local/bin/openshot-qt", line 11, in <module>
ERROR logger: load_entry_point('openshot-qt==2.5.1.dev2', 'gui_scripts', 'openshot-qt')()
ERROR logger:   File "/usr/local/lib/python3.7/dist-packages/openshot_qt-2.5.1.dev2-py3.7.egg/openshot_qt/launch.py", line 140, in main
ERROR logger: app = OpenShotApp(argv)
ERROR logger:   File "/usr/local/lib/python3.7/dist-packages/openshot_qt-2.5.1.dev2-py3.7.egg/openshot_qt/classes/app.py", line 137, in __init__
ERROR logger: from classes import exceptions
ERROR logger:   File "/usr/local/lib/python3.7/dist-packages/openshot_qt-2.5.1.dev2-py3.7.egg/openshot_qt/classes/exceptions.py", line 34, in <module>
ERROR logger: from classes.metrics import track_exception_stacktrace, track_metric_error
ERROR logger:   File "/usr/local/lib/python3.7/dist-packages/openshot_qt-2.5.1.dev2-py3.7.egg/openshot_qt/classes/metrics.py", line 83, in <module>
ERROR logger: "cd1": openshot.OPENSHOT_VERSION_FULL,  # Dimension 1: libopenshot version
ERROR logger: AttributeError
ERROR logger: :
ERROR logger: module 'openshot' has no attribute 'OPENSHOT_VERSION_FULL'
INFO app:             OpenShot's session ended            
INFO app:             Fri Jan 29 17:32:25 2021            
INFO app: ================================================
```
which can be fixed by updating libopenshot probably, which I will try. I was just thinking it would be easier for everyone to just be able to click install rather than update it themselves.

**Comment by SuperPi911** [comment]
openshot can run on pi4 8gb overclocked at 2147   and you cannot do more than 360p  withowt lag and crash

**Comment by Pythonic456** [comment]
@SuperPi911 Is that the latest version of OpenShot?

**Comment by Itai-Nelken** [comment]
video editing on the pi is really bad, I got the best performance out of Kdenlive.

**Comment by SuperPi911** [comment]
> @SuperPi911 Is that the latest version of OpenShot? 

Yes

**Comment by Itai-Nelken** [comment]
> > @SuperPi911 Is that the latest version of OpenShot?
> 
> Yes

latest version from `apt` or real latest version?
if real latest version how did you get it working?

**Comment by SuperPi911** [comment]
Apt

**Comment by Itai-Nelken** [comment]
> Apt

so thats a ancient version as @Pythonic456 said.

@Pythonic456 did you get the latest openshot working? 
can you send the commands you ran (even if they failed) please?

**Comment by Pythonic456** [comment]
The `apt` version is `2.4.3+dfsg1-1`, and the latest from [OpenShot](https://openshot.org/) appears to be `2.5.1`.

**Comment by Itai-Nelken** [comment]
> The `apt` version is `2.4.3+dfsg1-1` (at least, on 32-bit RPi OS), and the latest from [OpenShot](https://openshot.org/) appears to be `2.5.1`.

then its not that old, is it?

**Comment by Itai-Nelken** [comment]
also openshot has been very laggy and crashed frequently on all computers I tried it on (even on a pretty powerful computer).
I don't think it'll run very well on the pi considering how bad it ran on all other computers I tried it on.

**Comment by Pythonic456** [comment]
It's from 2018, and many improvements have been made since. And OpenShot has always worked well for me. If the latest version could be in Pi-Apps, then it would be so much nicer to use OpenShot.

**Comment by Itai-Nelken** [comment]
> It's from 2018, and many improvements have been made since. And OpenShot has always worked well for me. If the latest version could be in Pi-Apps, then it would be so much nicer to use OpenShot.

did you manage to run the latest version?

**Comment by Pythonic456** [comment]
@Itai-Nelken No, but I just need to update libopenshot too, which I will try.

**Comment by Itai-Nelken** [comment]
I just tried openshot and it is way better since last time I tried it. it will certainly be a good adition to pi-apps in my opinion.

**Comment by fabianmendes** [comment]
Any scripts so?  To install it properly.

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken No, but I just need to update libopenshot too, which I will try.

@Pythonic456 how did it go?

**Comment by Pythonic456** [comment]
@Itai-Nelken I am just cloning the repos and getting back to where I was, as I reset my RPi recently. I will let you know how it goes 👍

**Comment by Pythonic456** [comment]
Well, I have got as far as compiling libopenshot-audio, where I get this error:
```pi@raspberrypi4b:~/Openshot/libopenshot-audio/build $ make install
[ 77%] Built target openshot-audio
[ 88%] Linking CXX executable openshot-audio-test-sound
/usr/bin/ld: ../libopenshot-audio.so.0.2.0: undefined reference to `__atomic_fetch_xor_8'
/usr/bin/ld: ../libopenshot-audio.so.0.2.0: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../libopenshot-audio.so.0.2.0: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../libopenshot-audio.so.0.2.0: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/openshot-audio-test-sound.dir/build.make:87: src/openshot-audio-test-sound] Error 1
make[1]: *** [CMakeFiles/Makefile2:151: src/CMakeFiles/openshot-audio-test-sound.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Do you know how to fix this?

**Comment by Pythonic456** [comment]
Also, what I don't get, is that OpenShot could make an AppImage for RPi OS 32-bit. I think this would expand their user base a lot. Maybe I could ask @jonoomph if he would make one.

**Comment by Pythonic456** [comment]
I thought about using wine with box86, and it seems to install just fine, but then when trying to launch it this happens:
```pi@raspberrypi4b:~/Downloads $ wine OpenShot-v2.5.1-x86.exe 
Box86 with Dynarec v0.2.1 9a483890 built on Mar 12 2021 10:21:57
Box86 with Dynarec v0.2.1 9a483890 built on Mar 12 2021 10:21:57
00f0:fixme:process:SetProcessDEPPolicy (1): stub
00f0:fixme:thread:GetThreadUILanguage : stub, returning default language.
00f0:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0031D91C, 00000000 0031D944
00f0:fixme:nls:get_dummy_preferred_ui_language (0x38 0031D91C 00000000 0031D944) returning a dummy value (current locale)
00f0:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0031D91C, 00B8A680 0031D944
00f0:fixme:nls:get_dummy_preferred_ui_language (0x38 0031D91C 00B8A680 0031D944) returning a dummy value (current locale)
Box86 with Dynarec v0.2.1 9a483890 built on Mar 12 2021 10:21:57
010c:fixme:process:SetProcessDEPPolicy (1): stub
010c:fixme:thread:GetThreadUILanguage : stub, returning default language.
010c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0031D968, 00000000 0031D990
010c:fixme:nls:get_dummy_preferred_ui_language (0x38 0031D968 00000000 0031D990) returning a dummy value (current locale)
010c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0031D968, 00D4A680 0031D990
010c:fixme:nls:get_dummy_preferred_ui_language (0x38 0031D968 00D4A680 0031D990) returning a dummy value (current locale)
010c:fixme:wtsapi:WTSRegisterSessionNotification Stub 00040856 0x00000000
010c:fixme:uxtheme:BufferedPaintInit Stub ()
010c:fixme:win:DisableProcessWindowsGhosting : stub
010c:fixme:graphics:ShutdownBlockReasonDestroy (0x40856): stub
010c:fixme:graphics:ShutdownBlockReasonCreate (0x40856, L"Installing"): stub
010c:fixme:msg:ChangeWindowMessageFilterEx 0x4086e c060 1 (nil)
010c:fixme:msg:ChangeWindowMessageFilterEx 0x5086e c060 1 (nil)
010c:fixme:rstrtmgr:RmStartSession 0065B06C, 0, 0065B070 stub!
010c:fixme:graphics:ShutdownBlockReasonDestroy (0x40856): stub
010c:fixme:graphics:ShutdownBlockReasonCreate (0x40856, L"Installing OpenShot Video Editor."): stub
010c:fixme:msg:ChangeWindowMessageFilterEx 0x6086e c060 1 (nil)
010c:fixme:msg:ChangeWindowMessageFilterEx 0x7086e c060 1 (nil)
010c:fixme:msg:ChangeWindowMessageFilterEx 0x508b4 c060 1 (nil)
010c:fixme:msg:ChangeWindowMessageFilterEx 0x608b4 c060 1 (nil)
010c:fixme:shell:SHAutoComplete stub
010c:fixme:rstrtmgr:RmRegisterResources -559038737, 1000, 011E2350, 0, 00000000, 0, 00000000 stub!
010c:fixme:rstrtmgr:RmRegisterResources -559038737, 1000, 011E2350, 0, 00000000, 0, 00000000 stub!
010c:fixme:rstrtmgr:RmRegisterResources -559038737, 951, 011E2350, 0, 00000000, 0, 00000000 stub!
010c:fixme:rstrtmgr:RmGetList -559038737, 0031F2C8, 0031F2CC, 011BE360, 0031F2C4 stub!
010c:fixme:explorerframe:taskbar_list_SetProgressValue iface 015E7A48, hwnd 00040856, ullCompleted 0, ullTotal 350 stub!
010c:fixme:sfc:SfcIsFileProtected (00000000, L"C:\\Program Files\\OpenShot Video Editor\\unins000.exe") stub
010c:fixme:explorerframe:taskbar_list_SetProgressState iface 015E7A48, hwnd 00040856, flags 0 stub!
Box86 with Dynarec v0.2.1 9a483890 built on Mar 12 2021 10:21:57
wine: Unhandled page fault on read access to 00000000 at address 63FB1050 (thread 0114), starting debugger...
0114:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 272 108" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger
0124:fixme:netsh:wmain stub: L"C:\\windows\\system32\\netsh.exe" L"advfirewall" L"firewall" L"add" L"rule" L"name=OpenShot Video Editor" L"program=C:\\Program Files\\OpenShot Video Editor\\openshot-qt.exe" L"dir=in" L"action=allow" L"enable=yes"
wine: Unhandled page fault on read access to 00000000 at address 634E5050 (thread 011c), starting debugger...
011c:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 280 108" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger
wine: Unhandled page fault on read access to 00000000 at address 63206050 (thread 0134), starting debugger...
0134:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 304 116" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger
Box86 with Dynarec v0.2.1 9a483890 built on Mar 12 2021 10:21:57
010c:fixme:rstrtmgr:RmEndSession 3735928559 stub!
010c:fixme:graphics:ShutdownBlockReasonDestroy (0x40856): stub
010c:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 00040856
010c:fixme:uxtheme:BufferedPaintUnInit Stub ()
pi@raspberrypi4b:~/Downloads $ Loaded modules from current directory: C:\Program Files\OpenShot Video Editor
         app:INFO ------------------------------------------------
         app:INFO             Fri Mar 12 18:10:16 2021            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Windows-7-6.1.7601
         app:INFO processor: x86 Family 6 Model 0 Stepping 1, GenuineIntel
         app:INFO machine: x86
         app:INFO python version: 3.7.4
         app:INFO qt5 version: 5.12.4
         app:INFO pyqt5 version: 5.12.3
014c:fixme:nls:get_dummy_preferred_ui_language (0x8 0065EFC0 0065EFE0 0065EFC4) returning a dummy value (current locale)
    language:INFO Qt Detected Languages: ['en-GB']
    language:INFO LANG Environment Variable: en_GB.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
014c:err:module:import_dll Library libjasper-4.dll (which is needed by L"C:\\Program Files\\OpenShot Video Editor\\imageformats\\qjp2.dll") not found
014c:err:module:import_dll Library libtiff-5.dll (which is needed by L"C:\\Program Files\\OpenShot Video Editor\\imageformats\\qtiff.dll") not found
014c:err:module:import_dll Library libwebpdemux-2.dll (which is needed by L"C:\\Program Files\\OpenShot Video Editor\\imageformats\\qwebp.dll") not found
     ui_util:INFO Initializing UI for MainWindow
014c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
     version:INFO Found current version: {"openshot_version": "2.5.1"}
effects_model:INFO updating effects model.
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
[3] ???
[4] ???
[5] ???
[6] ???
[7] ???
[8] ???
[9] ???
[10] ???
014c:err:dbghelp:SymCleanup this process has not had SymInitialize() called for it!
---- End of Stack Trace ----
```

Could this be something to do with `winedbg`?

**Comment by Itai-Nelken** [comment]
I opened a issue in the openshot repo asking for official support for arm: https://github.com/OpenShot/openshot-qt/issues/4048

**Comment by gl91306** [comment]
openshot works and it works perfectly for me 720p 30fps

**Comment by gl91306** [comment]
> openshot can run on pi4 8gb overclocked at 2147 and you cannot do more than 360p withowt lag and crash

O-O what the

**Comment by gl91306** [comment]
sudo apt-get install openshot. thats it.

**Comment by Pythonic456** [comment]
@gl91306 We want a newer version of OpenShot for RPi OS. That is what this thread is for, really.
@SuperPi911  I can do 4K UHD 60FPS without lagging or crashing on Pi 4B 4G of RAM, can I help with this?

**Comment by Botspot** [comment]
Closed due to 24 days of inactivity, and the perception that there's no end in sight to get it working.

**Comment by gl91306** [comment]
The latest version IS available, but not for buster. its only availabe for bullseye

**Comment by Itai-Nelken** [comment]
right, on debian bullseye the latest release is available:
```
openshot-qt/unstable,unstable 2.5.1+dfsg1-1 all
  create and edit videos and movies
```

**Comment by Pythonic456** [comment]
Thanks!

**Comment by Rak1ta** [comment]
@Botspot From what I understand, you are now adding applications from the package manager.
[OpenShot Video Editor.zip](https://github.com/Botspot/pi-apps/files/8784700/OpenShot.Video.Editor.zip)
