### ISSUE TITLE
AndroidBuddy ins`t opening 

### ISSUE THREAD

**Issue by SuperPi911** [Botspot/pi-apps#304]
pi@raspberrypi:~ $ python3 /home/pi/droidbuddy/main.py
Traceback (most recent call last):
  File "/home/pi/droidbuddy/main.py", line 13, in <module>
    window.tk.call('wm', 'iconphoto', window._w, tk.PhotoImage(file='images/icon.png'))
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "images/icon.png": no such file or directory
pi@raspberrypi:~ $

**Comment by techcoder20** [comment]
You can fix this by modifying the code for the gui or simpler just run the command from inside the directory
```
cd ~/droidbuddy
python3 main.py
```

If you do want to modify the code to keep using the `python3 /home/pi/droidbuddy/main.py` command
search for the lines in the code (main.py) which use `image/...` and replace that with `/home/pi/droidbuddy/image/...`

**Comment by SuperPi911** [comment]
Can you send the modyfied main.py file?

**Comment by techcoder20** [comment]
```
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
from PIL import ImageTk, Image
import subprocess
import time
from pathlib import Path
from datetime import datetime

window = tk.Tk()
window.title("AndroidBuddy")
window.resizable(False, False)
window.tk.call('wm', 'iconphoto', window._w, tk.PhotoImage(file='/home/pi/droidbuddy/images/icon.png'))

info = tk.Frame(bg="white")
buttons = tk.Frame(bg="white", padx=20, pady=20)

# Commands
def installAPK():
    apk = filedialog.askopenfile(mode="r", initialdir="/")
    subprocess.Popen(f"adb install -r {apk.name}", shell=True)
def viewScreen():
    subprocess.Popen("scrcpy")
def fileRecover():
    exec(open('recovery.py').read())
def fileUpload():
    files = filedialog.askopenfiles(mode="r", initialdir="/").replace(" ", "_")
    if not files:
        return
    for i in range(len(files)):
        subprocess.run(f"adb push {files[i].name} /sdcard/DB-Transfer/{files[i].name}", shell=True)
    messagebox.showinfo("Information","Transfer successful, find files in DB-Transfer folder on device")
def advancedCtrl():
    exec(open('control.py').read())

# Information
titleimg = ImageTk.PhotoImage(Image.open("/home/pi/droidbuddy/images/logo2.png"))
title = tk.Label(
    image = titleimg,
    height = 100,
    width=30,
    bg="white"
)
warning = tk.Label(
    master=info,
    text="This program will only work if\nyou have USB Debugging enabled!",
    fg="white",bg="red",
    height=2
)

# Main menu
button = tk.Button(
    master=buttons,
    text="Install .APK",
    width=20,height=2,
    fg="white",bg="#08a300",
    relief=tk.FLAT,
    command=installAPK
)
button2 = tk.Button(
    master=buttons,
    text="Back up files",
    width=20,height=2,
    fg="white",bg="#4287f5",
    relief=tk.FLAT,
    command=fileRecover
)
button3 = tk.Button(
    master=buttons,
    text="View screen",
    width=20,height=2,
    fg="white",bg="orange",
    relief=tk.FLAT,
    command=viewScreen
)
button4 = tk.Button(
    master=buttons,
    text="Upload files",
    width=20,height=2,
    fg="white",bg="#4287f5",
    relief=tk.FLAT,
    command=fileUpload
)
button5 = tk.Button(
    master=buttons,
    text="Advanced device control",
    width=20,height=2,
    fg="white",bg="orange",
    relief=tk.FLAT,
    command=advancedCtrl
)

# Grids
button.grid(row=0, column=0)
button2.grid(row=0, column=1)
button3.grid(row=1, column=0)
button4.grid(row=1, column=1)
button5.grid(row=2, column=0)

# Packs
title.pack(fill=tk.X)
warning.pack(fill=tk.X)

info.pack(fill=tk.X)
buttons.pack()

window.mainloop()
```

sry was unable to upload the file, just replace the text in main.py with this

**Comment by SuperPi911** [comment]
now works, thank you!

**Comment by Botspot** [comment]
@SuperPi911 Did Androidbuddy launch OK from the Start Menu?

If not, I can try to fix it.

**Comment by SuperPi911** [comment]
With the fix is launching and normal ins't launching.

**Comment by techcoder20** [comment]
@Botspot maybe we could use some sed commands to modify the script after installation. Not sure if that's the best solution though 😕

**Comment by Botspot** [comment]
> @Botspot maybe we could use some sed commands to modify the script after installation. Not sure if that's the best solution though

Or we could just modify the menu button to `cd` the correct directory. ;)

**Comment by Botspot** [comment]
Okay it should be fixed now.

**Comment by techcoder20** [comment]
@Botspot I think this issue can be closed now
